name: Build Keycloak Image

concurrency:
  group: keycloak-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      keycloak_image_ref:
        description: "The commit hash of the keycloak image to be build"
        # renovate: datasource=custom.bitnamiKeycloakCommits depName=bitnami/containers
        default: "411bc7189c51ca61415abecaf1be8ab13ab24592"
        required: true
      keycloak_image_tag:
        description: "The keycloak tag to be created"
        # renovate: datasource=custom.bitnamiKeycloakTagFromDockerfile depName=bitnami/containers versioning=loose
        default: "26.5.2-debian-12-r0"
        required: true
      keycloak_image_context_path:
        description: "The path to the directory holding the dockerfile"
        default: "bitnami/keycloak/26/debian-12"
        required: true

permissions:
  contents: read

jobs:
  build-image:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed for docker/build-push-action to push the image to the registry
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: bitnami/containers
          ref: ${{ github.event.inputs.keycloak_image_ref }}
          fetch-depth: '1'
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ghcr.io/platform-mesh/upstream-images/keycloak:${{ github.event.inputs.keycloak_image_tag }}
          context: ${{ github.event.inputs.keycloak_image_context_path }}
